### ISSUE TITLE
Tests fail on macOS and windows

### ISSUE THREAD

**Issue by dtrosien** [dtrosien/data-collector#39]
The following tests fail on macOS and windows:

- collectors::source_apis::sec_companies::test::file_is_not_loaded_when_new
- collectors::source_apis::sec_companies::test::given_new_file_when_checked_then_returns_false

failures:

---- collectors::source_apis::sec_companies::test::given_new_file_when_checked_then_returns_false stdout ----
thread 'collectors::source_apis::sec_companies::test::given_new_file_when_checked_then_returns_false' panicked at src/collectors/source_apis/sec_companies.rs:368:9:
assertion `left == right` failed
  left: true
 right: false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- collectors::source_apis::sec_companies::test::file_is_not_loaded_when_new stdout ----
thread 'collectors::source_apis::sec_companies::test::file_is_not_loaded_when_new' panicked at src/collectors/source_apis/sec_companies.rs:489:9:
assertion `left == right` failed
  left: 2511
 right: 3109

**Comment by Telijas** [comment]
The issue is that the copy command works differently in the OS's; while on Linux the content gets copied on the other OS's the files metadata gets also copied, making a 'new' file to an 'old' file.
Solution approach: Fix metadata after content copying.
